language: php

cache:
  directories:
    - ~/.composer/cache

php:
  - 5.5

sudo: false

install:
  - composer self-update
  - export COMPOSER_ROOT_VERSION=1.1.x-dev
  - composer install --no-progress --prefer-dist

script: ./bin/phpunit

addons:
  code_climate:
    repo_token: ba11992087a6a701b9ff4a8b009495ed075a1152087e546b534241bfea1f6644 

after_script:
  - ./bin/test-reporter
